### ISSUE TITLE
Error with different dataset

### ISSUE THREAD

**Issue by rafaelmarconiramos** [Shathe/Semantic-Segmentation-Tensorflow-Eager#3]
Hi,

I change the example to use my dataset.
I have just one class (the mask has two colors, black and with).
The image has 140x140 pixels. 

**n_classes = 1
dataset_path = 'seg'**
loader = Loader.Loader(dataFolderPath=dataset_path, n_classes=n_classes, problemType='segmentation', width=**140**,
		height=**140**, ignore_label=n_classes)
model = MnasnetEager.MnasnetFC(num_classes=n_classes)
optimizer = tf.train.AdamOptimizer(0.001)
train(loader=loader, model=model, epochs=20, batch_size=8)
get_params(model)

The result generates an error:
Using TensorFlow backend.
Reading files...
Structuring test and train files...
Loaded 92 training samples
Loaded 10 testing samples
Dataset contains 1 classes
epoch: 0
Traceback (most recent call last):
  File "train_eager_seg.py", line 109, in <module>
    train(loader=loader, model=model, epochs=20, batch_size=1)
  File "train_eager_seg.py", line 44, in train
    x, y, mask = loader.get_batch(size=batch_size, train=True, augmenter=augmenter)
  File "/pylon5/ac3uump/rafaelmr/Semantic-Segmentation-Tensorflow-Eager/Loader.py", line 377, in get_batch
    return self._get_batch_segmentation(size=size, train=train, augmenter=augmenter)
  File "/pylon5/ac3uump/rafaelmr/Semantic-Segmentation-Tensorflow-Eager/Loader.py", line 296, in _get_batch_segmentation
    y = to_categorical(y, num_classes=self.n_classes+1)
  File "/home/rafaelmr/.conda/envs/seg1/lib/python2.7/site-packages/keras/utils/np_utils.py", line 32, in to_categorical
    categorical[np.arange(n), y] = 1
**IndexError: index 255 is out of bounds for axis 1 with size 2**

Probably the error is associated with the number of the classes.
I put the correct number of the classes. I try others numbers, but the problem still the same.
Do I need to code another place?

**Comment by Shathe** [comment]
This repository is just an example (not a tutorial) that's why I did not commented anything about my Loader class.

The Loader class, loads the image labels but, they need to have values from 0 to the number of classes - 1. That is: if You have 2 classes the labels must be 0 and 1. If you have 10 classes, the labels must be 0,1,2,3,4,5,6,7,8,9.
Other label values will be  ignore (new commit, pull new changes)

**Comment by rafaelmarconiramos** [comment]
Thanks. I changed the code start, but now generate another error:

Traceback (most recent call last):
  File "train_eager_seg.py", line 109, in <module>
    train(loader=loader, model=model, epochs=20, batch_size=8)
  File "train_eager_seg.py", line 50, in train
    loss = tf.losses.softmax_cross_entropy(y, y_, weights=mask)
  File "/home/rafaelmr/.conda/envs/seg1/lib/python2.7/site-packages/tensorflow/python/ops/losses/losses_impl.py", line 793, in softmax_cross_entropy
    logits.get_shape().assert_is_compatible_with(onehot_labels.get_shape())
  File "/home/rafaelmr/.conda/envs/seg1/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 847, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (8, 160, 160, 2) and (8, 140, 140, 2) are incompatible

All images are 140x140, and I configured the parameters for that size.
Why the model generates a shape like (8, 160, 160, 2)?
Do I need to know something more about the data? Or the model?
I looked for in the project files, but I didn´t find.

Thanks for your attention.

**Comment by Shathe** [comment]
That is something concerning your code and yes, it's about sizes/shapes

Somewhere you must have specified the 160x160 (at code level)  or the images are 140x140.

The image size is specified here https://github.com/Shathe/Semantic-Segmentation-Tensorflow-Eager/blob/master/train_eager.py#L100

The network input shape (input_shape parameter) here  https://github.com/Shathe/Semantic-Segmentation-Tensorflow-Eager/blob/master/train_eager.py#L104

Please, take your time to code and to  **debug** the code

**Comment by rafaelmarconiramos** [comment]
Sorry.

In this line generates the problem: https://github.com/Shathe/Semantic-Segmentation-Tensorflow-Eager/blob/333b1a879295e56d9615fb191c91d228c446c837/train_eager.py#L48

x,y, mask are  tf.Tensor(shape=(8, 140, 140, 2), dtype=uint8)
y_ is  tf.Tensor(shape=(8, 160, 160, 2), dtype=float32)

I will try to understand what the line 48 do.

**Comment by Shathe** [comment]
y_ is the output, so the output has that size. 
I cannot help more without seen your edited code.

**Comment by rafaelmarconiramos** [comment]
With the architecture of MnasnetFC, the code works just with the image sizes that are multiples of 32.
Look the shapes of your example (each execution of the out in  MnasnetFC.call)
initial: (8, 112, 112, 32)
initial2: (8, 112, 112, 32)
initial3: (8, 112, 112, 32)
initial4: (8, 112, 112, 32)
initial5: (8, 112, 112, 16)
blocks: (8, 56, 56, 24)
blocks: (8, 56, 56, 24)
blocks: (8, 56, 56, 24)
blocks: (8, 28, 28, 40)
blocks: (8, 28, 28, 40)
blocks: (8, 28, 28, 40)
blocks: (8, 14, 14, 80)
blocks: (8, 14, 14, 80)
blocks: (8, 14, 14, 80)
blocks: (8, 14, 14, 96)
blocks: (8, 14, 14, 96)
blocks: (8, 7, 7, 192)
blocks: (8, 7, 7, 192)
blocks: (8, 7, 7, 192)
blocks: (8, 7, 7, 192)
blocks: (8, 7, 7, 320)
initial6: (8, 7, 7, 1152)
up: (8, 14, 14, 1152)
up: (8, 14, 14, 192)
up: (8, 14, 14, 192)
up: (8, 28, 28, 192)
up: (8, 28, 28, 80)
up: (8, 28, 28, 80)
up: (8, 56, 56, 80)
up: (8, 56, 56, 40)
up: (8, 112, 112, 40)
up: (8, 112, 112, 24)
up: (8, 224, 224, 24)
final: (8, 224, 224, 11)

Basic it decreases the shape dividing by two. After it increases the shape multiplying by two. It does this operation five times then it needs a multiply of 32. 
In my case the division by two has rest then when it executes the multiplication don´t finish with correct number.

initial: (8, 70, 70, 32)
initial2: (8, 70, 70, 32)
initial3: (8, 70, 70, 32)
initial4: (8, 70, 70, 32)
initial5: (8, 70, 70, 16)
blocks: (8, 35, 35, 24)
blocks: (8, 35, 35, 24)
blocks: (8, 35, 35, 24)
blocks: (8, 18, 18, 40)
blocks: (8, 18, 18, 40)
blocks: (8, 18, 18, 40)
blocks: (8, 9, 9, 80)
blocks: (8, 9, 9, 80)
blocks: (8, 9, 9, 80)
blocks: (8, 9, 9, 96)
blocks: (8, 9, 9, 96)
blocks: (8, 5, 5, 192)
blocks: (8, 5, 5, 192)
blocks: (8, 5, 5, 192)
blocks: (8, 5, 5, 192)
blocks: (8, 5, 5, 320)
initial6: (8, 5, 5, 1152)
up: (8, 10, 10, 1152)
up: (8, 10, 10, 192)
up: (8, 10, 10, 192)
up: (8, 20, 20, 192)
up: (8, 20, 20, 80)
up: (8, 20, 20, 80)
up: (8, 40, 40, 80)
up: (8, 40, 40, 40)
up: (8, 80, 80, 40)
up: (8, 80, 80, 24)
up: (8, 160, 160, 24)
final: (8, 160, 160, 2)

Correct?
My code:
if __name__ == "__main__":

        n_classes = 2
        dataset_path = 'seg'
        loader = Loader.Loader(dataFolderPath=dataset_path, n_classes=n_classes, problemType='segmentation', width=140,
                        height=140, ignore_label=n_classes)

        # build model and optimizer
        model = MnasnetEager.MnasnetFC(num_classes=n_classes)

        # optimizer
        optimizer = tf.train.AdamOptimizer(0.001)

        train(loader=loader, model=model, epochs=20, batch_size=8)
        get_params(model)
