### ISSUE TITLE
Bilinear Upsample

### ISSUE THREAD

**Issue by bhack** [Shathe/Semantic-Segmentation-Tensorflow-Eager#4]
Is available upstream now? https://github.com/keras-team/keras-contrib/pull/264#discussion_r222748992

**Comment by Shathe** [comment]
I don't understand the question, what do you mean?

**Comment by bhack** [comment]
See https://github.com/keras-team/keras/releases/tag/2.2.3 now we are at 2.2.4 but probably TF has still not upgrade its keras version.

**Comment by bhack** [comment]
So probably on the next TF sync you could use directly interpolation argument in UpSampling2D layer in tf.keras but I am still not sure if in tf 1.12
