### ISSUE TITLE
Multiprocess load batch

### ISSUE THREAD

**Issue by Shathe** [Shathe/Semantic-Segmentation-Tensorflow-Eager#5]
Add to the Loaders _get_batch_ function the possibility of loading it in another process. 

If its the first time to call it, load a batch as normal and  creates anew process to load next batch

it is not the first time to load it, creates a new process to load next batch and waits for the previous loaded batch in the queue.

https://stackoverflow.com/questions/2046603/is-it-possible-to-run-function-in-a-subprocess-without-threading-or-writing-a-se

compare both performances

**Comment by bhack** [comment]
Generally the dataset API is already highly optimized.

**Comment by Shathe** [comment]
Yeah, you're right
I am currently using my custom Loader for loading and performing data augmentation but... I think it's about time to move into the data.Dataset API haha
I am gonna open another issue for that

**Comment by bhack** [comment]
https://www.tensorflow.org/performance/datasets_performance

**Comment by Shathe** [comment]
Nevertheless... I just saw it andd... Do you know if you can use it when the data does not fit into RAM? I mean, if you cannot load the entire dataset at once... You can still use the Dataset API?

**Comment by bhack** [comment]
Yes off course

**Comment by bhack** [comment]
If you want to continue in Eager mode check also https://www.tensorflow.org/tutorials/eager/eager_basics#datasets

**Comment by Shathe** [comment]
You know how? I mean, can you provide me a link or a function name or something? I'll try to search on internet and on the guide you linked in previous messages too

**Comment by bhack** [comment]
Almos all the real datasets don't fit in memory so you will find many many dataset API examples. Just to mention one https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/contrib/eager/python/examples/generative_examples/image_captioning_with_attention.ipynb

**Comment by Shathe** [comment]
I mean, referring to the size of the dataset

**Comment by bhack** [comment]
There the dataset don't fit in memory

**Comment by Shathe** [comment]
Thanks a lot!
